### ISSUE TITLE
Read version_option from the pyproject.toml

### ISSUE THREAD

**Issue by mrmeszaros** [pallets/click#2572]
`@click.version_option()` should be able to get the version value from a `pyproject.toml` file.

Currently using `version_option` in a project that uses pyproject.toml (eg.: `poetry`) one have to specify the version twice - or at least the package name twice, by using:
```python
# cli.py
@click.version_option(package_name='my-awesome-pkg')
```
```toml
# pyproject.toml
[tool.poetry]
name = "my-awesome-pkg"
version = "0.1.0"
```

It would be nice if click could figure it out based on the `pyproject.toml` - without the need to specify the package name explicitly. Like maybe:
```python
@click.version_option(from_pyproject=True)
# or
@click.version_option(from_source='pyproject_toml')
```
